spring:
  datasource:
    url: jdbc:h2:mem:testdb;
    username: sa
    password:
    driver-class-name: org.h2.Driver
    data: classpath:/data.sql
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
#  redis:
#    host: 127.0.0.1
#    port: 6379
#  session:
#    store-type: redis